### ISSUE TITLE
NonTemplatedInputDirException when trying to create instance

### ISSUE THREAD

**Issue by jrderuiter** [snakemake-workflows/cookiecutter-snakemake-workflow#1]
When trying to instantiate the template using cookiecutter, I get the following exception:

```
Traceback (most recent call last):
  File "/Users/Julian/Anaconda/bin/cookiecutter", line 6, in <module>
    sys.exit(cookiecutter.cli.main())
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/cookiecutter/generate.py", line 253, in generate_files
    template_dir = find_template(repo_dir)
  File "/Users/Julian/Anaconda/lib/python3.6/site-packages/cookiecutter/find.py", line 36, in find_template
    raise NonTemplatedInputDirException
cookiecutter.exceptions.NonTemplatedInputDirException
```

This is using cookiecutter 1.5.1 on Python 3.6.

Isn't this exception occurring because of the structure of the template? Most examples I have seen have the actual template in a subdirectory (see https://github.com/drivendata/cookiecutter-data-science for example), which is named after the repo name or something similar.

**Comment by jrderuiter** [comment]
With the fixes in this pull-request I am able to properly instantiate the template.

**Comment by johanneskoester** [comment]
Thanks! I have merged it.
